# Generated by Django 5.2.1 on 2025-06-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swap_tthh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backups',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_equipo', models.CharField(max_length=60, verbose_name='Equipo (pc/notebook)')),
                ('b_nombre', models.CharField(max_length=80, verbose_name='Nombre del Backup')),
                ('b_estado', models.CharField(max_length=45, verbose_name='Estado(activo/inactivo)')),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'db_table': 'backups',
                'ordering': ['b_disco'],
            },
        ),
        migrations.CreateModel(
            name='Backupsdia',
            fields=[
                ('bd_id', models.AutoField(primary_key=True, serialize=False)),
                ('bd_dia', models.CharField(max_length=45, verbose_name='Dia del Backup')),
            ],
            options={
                'verbose_name': 'Dia del Backup',
                'verbose_name_plural': 'Dias de los Backups',
                'db_table': 'backupsdia',
            },
        ),
        migrations.CreateModel(
            name='Backupsestado',
            fields=[
                ('be_id', models.AutoField(primary_key=True, serialize=False)),
                ('be_estado', models.CharField(max_length=45, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado del Backup',
                'verbose_name_plural': 'Estados de los Backups',
                'db_table': 'backupsestado',
                'ordering': ['be_estado'],
            },
        ),
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('disco_id', models.AutoField(primary_key=True, serialize=False)),
                ('disco_nombre', models.CharField(max_length=60, verbose_name='Nombre del Disco')),
            ],
            options={
                'verbose_name': 'Disco',
                'verbose_name_plural': 'Discos',
                'db_table': 'discos',
                'ordering': ['disco_nombre'],
            },
        ),
        migrations.CreateModel(
            name='InventarioinformaticaCategoria',
            fields=[
                ('iic_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('iic_nombre', models.CharField(max_length=150, verbose_name='Articulo')),
            ],
            options={
                'verbose_name': 'Categoria (inventario)',
                'verbose_name_plural': 'Categorias (inventario)',
                'db_table': 'inventarioinformatica_categoria',
                'ordering': ['iic_nombre'],
            },
        ),
        migrations.CreateModel(
            name='InventarioinformaticaDeposito',
            fields=[
                ('iid_id', models.AutoField(primary_key=True, serialize=False)),
                ('iid_nombre', models.CharField(max_length=60, verbose_name='Deposito')),
            ],
            options={
                'verbose_name': 'Deposito (inventario)',
                'verbose_name_plural': 'Depositos (inventario)',
                'db_table': 'inventarioinformatica_deposito',
                'ordering': ['iid_nombre'],
            },
        ),
        migrations.CreateModel(
            name='InventarioinformaticaEstado',
            fields=[
                ('iie_id', models.AutoField(primary_key=True, serialize=False)),
                ('iie_nombre', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado (inventario)',
                'verbose_name_plural': 'Estados (inventario)',
                'db_table': 'inventarioinformatica_estado',
                'ordering': ['iie_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimientoestado',
            fields=[
                ('me_id', models.AutoField(primary_key=True, serialize=False)),
                ('me_estado', models.CharField(max_length=60, verbose_name='Estado de Mantenimiento')),
            ],
            options={
                'verbose_name': 'Estado de Mantenimiento',
                'verbose_name_plural': 'Estados de Mantenimientos',
                'db_table': 'mantenimientoestado',
                'ordering': ['me_estado'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoTipo',
            fields=[
                ('mt_id', models.AutoField(primary_key=True, serialize=False)),
                ('mt_nombre', models.CharField(max_length=70, verbose_name='Tipo de Mantenimiento')),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimientos',
                'db_table': 'mantenimiento_tipo',
                'ordering': ['mt_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipoequipo',
            fields=[
                ('tipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipe_nombre', models.CharField(max_length=100, verbose_name='Tipo de Equipo')),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipos',
                'db_table': 'tipoequipo',
                'ordering': ['tipe_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Backupsproceso',
            fields=[
                ('bp_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('bp_b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.backups', verbose_name='Backup')),
                ('bp_bd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.backupsdia', verbose_name='Dia del Backup')),
                ('bp_be', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.backupsestado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Backup en Proceso',
                'verbose_name_plural': 'Backups en Procesos',
                'db_table': 'backupsproceso',
                'ordering': ['bp_bd'],
            },
        ),
        migrations.CreateModel(
            name='Backupshechos',
            fields=[
                ('bh_id', models.AutoField(primary_key=True, serialize=False)),
                ('bh_fecha', models.DateField(verbose_name='Fecha del Backup')),
                ('bh_bp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.backupsproceso', verbose_name='Backup')),
            ],
            options={
                'verbose_name': 'Backup Hecho',
                'verbose_name_plural': 'Backups Hechos',
                'db_table': 'backupshechos',
                'ordering': ['bh_fecha'],
            },
        ),
        migrations.AddField(
            model_name='backups',
            name='b_disco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.discos', verbose_name='Disco Correspondiente'),
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('eq_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('eq_numdeserie', models.CharField(max_length=45, verbose_name='Numero de Serie')),
                ('eq_usuario', models.CharField(blank=True, max_length=60, null=True, verbose_name='Usuario')),
                ('eq_contrasenna', models.CharField(blank=True, max_length=45, null=True, verbose_name='Contraseña')),
                ('eq_marca', models.CharField(blank=True, max_length=45, null=True, verbose_name='Marca')),
                ('eq_modelo', models.CharField(blank=True, max_length=45, null=True, verbose_name='Modelo')),
                ('eq_marcamonitor', models.CharField(blank=True, max_length=45, null=True, verbose_name='Marca del Monitor')),
                ('eq_pulgadamonitor', models.CharField(blank=True, max_length=45, null=True, verbose_name='Pulgadas del Monitor')),
                ('eq_placamadre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Placa Madre')),
                ('eq_grafica', models.CharField(blank=True, max_length=45, null=True, verbose_name='Tarjeta Grafica')),
                ('eq_discoduro', models.CharField(blank=True, max_length=45, null=True, verbose_name='Disco Duro')),
                ('eq_lectordisco', models.CharField(blank=True, max_length=45, null=True, verbose_name='Lector de Disco')),
                ('eq_audio', models.CharField(blank=True, max_length=45, null=True, verbose_name='Audio')),
                ('eq_sistemop', models.CharField(blank=True, max_length=45, null=True, verbose_name='Sistema Operativo')),
                ('eq_dpto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_tthh.departamentos', verbose_name='Departamento')),
                ('eq_tipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.tipoequipo', verbose_name='Tipo de Equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
                'ordering': ['eq_tipe'],
            },
        ),
        migrations.CreateModel(
            name='Funcionarioconequipo',
            fields=[
                ('fce_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('fce_equipo', models.CharField(max_length=60, verbose_name='Equipo (pc/notebook)')),
                ('fce_nombre_equipo', models.CharField(max_length=60, verbose_name='Nombre del Equipo')),
                ('fce_nombre_sati', models.CharField(max_length=60, verbose_name='Nombre en SATI')),
                ('fce_serie_sati', models.CharField(max_length=60, verbose_name='Serie en SATI')),
                ('fce_ip', models.CharField(max_length=60, verbose_name='IP')),
                ('fce_observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('fce_ruta_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
                ('fce_estado', models.CharField(max_length=60, verbose_name='Estado(activo/inactivo)')),
                ('fce_fun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_tthh.funcionarios', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Funcionario con Equipo',
                'verbose_name_plural': 'Funcionarios con Equipo',
                'db_table': 'funcionarioconequipo',
                'ordering': ['fce_fun'],
            },
        ),
        migrations.AddField(
            model_name='backups',
            name='b_fce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.funcionarioconequipo', verbose_name='Funcionario'),
        ),
        migrations.CreateModel(
            name='Inventarioinformatica',
            fields=[
                ('ii_id', models.AutoField(primary_key=True, serialize=False)),
                ('ii_cantidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad')),
                ('ii_descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('ii_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('ii_ruta_imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagen')),
                ('ii_iic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.inventarioinformaticacategoria', verbose_name='Articulo')),
                ('ii_iid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.inventarioinformaticadeposito', verbose_name='Deposito')),
                ('ii_iie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.inventarioinformaticaestado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Item Informatica',
                'verbose_name_plural': 'Inventario Informatica',
                'db_table': 'inventarioinformatica',
                'ordering': ['ii_iid'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimientocalendario',
            fields=[
                ('mc_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('mc_fecha', models.DateField(verbose_name='Fecha a Realizar')),
                ('mc_eq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.equipos', verbose_name='Equipo')),
                ('mc_me', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.mantenimientoestado', verbose_name='Estado')),
                ('mc_mt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.mantenimientotipo', verbose_name='Tipo de Mantenimiento')),
            ],
            options={
                'verbose_name': 'Fecha de Mantenimiento',
                'verbose_name_plural': 'Fechas de Mantenimientos',
                'db_table': 'mantenimientocalendario',
                'ordering': ['mc_fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_fecha', models.DateField(verbose_name='Fecha del Mantenimiento')),
                ('m_responsable', models.CharField(max_length=60, verbose_name='Responsable')),
                ('m_eq', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.equipos', verbose_name='Equipo')),
                ('m_mt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.mantenimientotipo', verbose_name='Tipo de Mantenimiento')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimiento',
                'ordering': ['m_fecha'],
            },
        ),
    ]
