# Generated by Django 5.2.1 on 2025-07-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_informatica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='accesorios',
            field=models.CharField(blank=True, default='-', max_length=200, null=True, verbose_name='Accesorios'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='antiviruz',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Antivirus'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='conexion_monitor',
            field=models.CharField(blank=True, default='-', max_length=70, null=True, verbose_name='Conexión del Monitor'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='cpu',
            field=models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='CPU'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='ip',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='mouse',
            field=models.CharField(blank=True, default='-', max_length=80, null=True, verbose_name='Mouse'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='nombre',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='nombre_equipo',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Nombre del Equipo'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='office',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Office'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='programas',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Programas'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='ram',
            field=models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='RAM'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='responsable',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='teclado',
            field=models.CharField(blank=True, default='-', max_length=80, null=True, verbose_name='Teclado'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='thunderbird',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Thunderbird'),
        ),
        migrations.AlterField(
            model_name='funcionarioconequipo',
            name='fce_nombre_sati',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='funcionarioconequipo',
            name='fce_serie_sati',
            field=models.CharField(max_length=60, verbose_name='Serie'),
        ),
    ]
