# Generated by Django 5.2.1 on 2026-02-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_informatica', '0002_equipos_accesorios_equipos_antiviruz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupsSemanaControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_week_start', models.DateField()),
            ],
        ),
    ]
