# Generated by Django 5.2.1 on 2026-02-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_informatica', '0003_backupssemanacontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupshechos',
            name='bh_week_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='backupshechos',
            constraint=models.UniqueConstraint(fields=('bh_bp', 'bh_week_start'), name='unique_backup_por_semana'),
        ),
    ]
