# Generated by Django 5.2.1 on 2026-05-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swap_informatica', '0004_backupshechos_bh_week_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupshechos',
            name='bh_bp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='swap_informatica.backupsproceso', verbose_name='Backup'),
        ),
        migrations.AlterField(
            model_name='backupshechos',
            name='bh_week_start',
            field=models.DateField(db_index=True, verbose_name='Semana (lunes)'),
        ),
    ]
