# """
# Django settings for swap project.

# Generated by 'django-admin startproject' using Django 5.2.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path
# import os


# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# #SECRET_KEY = 'django-insecure-yvf*6tb-yb#!lfglyiv!v95n2(l_g!hr4__wobp5ed5ehtu$cw'
# SECRET_KEY = os.environ.get("SECRET_KEY", "clave-insegura-por-defecto")

# # SECURITY WARNING: don't run with debug turned on in production!
# #DEBUG = True
# DEBUG = os.environ.get("DEBUG", "False") == "True"

# #ALLOWED_HOSTS = ['*']
# #ALLOWED_HOSTS = ['serpy.herokuapp.com', 'sertecti.com', 'localhost', '127.0.0.1']
# ALLOWED_HOSTS = ['sertecti.com', 'www.sertecti.com', 'serpy-17288fafdad2.herokuapp.com']


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'django.contrib.humanize',
#     'swap_home.apps.SwapHomeConfig',
#     'swap_informatica.apps.SwapInformaticaConfig',
#     'swap_tthh.apps.SwapTthhConfig',
#     'swap_porteria.apps.SwapPorteriaConfig',
#     'swap_serviciotecnico.apps.SwapServiciotecnicoConfig',
#     'swap_tecnico',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',#Para que Heroku lea archivos estaticos se instalo whitenoise
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'swap.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [
#             BASE_DIR / 'templates',  # Agrega aquí la ruta a tu carpeta global templates    
#         ],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'swap.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.mysql',
# #         #'NAME': 'swap_demo_2.3',
# #         #'NAME': 'swap_demo_2.6',
# #         'NAME': 'swap_3',
# #         'USER': 'root',
# #         'PASSWORD': 'admin',
# #         'HOST': 'localhost',  # o la dirección de tu servidor MySQL
# #         'PORT': '3306',  # o el puerto que estés usando
# #     }
# # }

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'swap',               # nombre de tu base de datos PostgreSQL
# #         'USER': 'postgres',           # usuario (normalmente "postgres" por defecto)
# #         'PASSWORD': 'admin',    # contraseña que usaste en la instalación
# #         'HOST': 'localhost',          # o IP del servidor PostgreSQL
# #         'PORT': '5432',               # puerto por defecto de PostgreSQL
# #     }
# # }

# # import dj_database_url

# # DATABASES = {
# #     'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
# # }
# import dj_database_url
# from decouple import config

# DATABASE_URL = config("DATABASE_URL")

# DATABASES = {
#     'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=not DEBUG)
# }




# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'es'

# TIME_ZONE = 'America/Argentina/Buenos_Aires'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/



# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATIC_URL = '/static/'

# # Activar compresión de archivos estáticos
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True



# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {  # ⬅ Manda la salida al sistema (Heroku la capta)
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'INFO',  # ⬅ Mostrá logs desde "INFO" hacia arriba
#     },
# }


import os#para imagenes
from pathlib import Path
import dj_database_url
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

# CONFIGURACIONES BÁSICAS
SECRET_KEY = config("SECRET_KEY", default="clave-insegura")
DEBUG = config("DEBUG", default=False, cast=bool)
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1").split(",") #Local
#ALLOWED_HOSTS = ['sertecti.com', 'www.sertecti.com', 'serpy-17288fafdad2.herokuapp.com']
#ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="serpy-17288fafdad2.herokuapp.com,sertecti.com,www.sertecti.com").split(",") #produccion
# APLICACIONES
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'swap_home.apps.SwapHomeConfig',
    'swap_informatica.apps.SwapInformaticaConfig',
    'swap_tthh.apps.SwapTthhConfig',
    'swap_porteria.apps.SwapPorteriaConfig',
    'swap_serviciotecnico.apps.SwapServiciotecnicoConfig',
    'swap_tecnico',
]

# MIDDLEWARE
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'swap.urls'

# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'swap.wsgi.application'

# DATABASE
DATABASE_URL = config("DATABASE_URL")
DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
}

# VALIDADORES DE CONTRASEÑA
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# CONFIGS REGIONALES
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# STATIC FILES
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# SEGURIDAD (solo si subís esto a producción real, en local no afecta)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# LOGS
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'INFO'},
}

#para imagenes
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')