# Generated by Django 5.2.1 on 2025-06-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swap_tthh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('cob_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('cob_nombre', models.CharField(max_length=200, verbose_name='Nombre del Cobrador')),
                ('cob_estado', models.CharField(max_length=50, verbose_name='Estado del Cobrador (activo/inactivo)')),
            ],
            options={
                'verbose_name': 'Cobrador',
                'verbose_name_plural': 'Cobradores',
                'db_table': 'cobrador',
                'ordering': ['cob_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estadoentrada',
            fields=[
                ('ee_id', models.AutoField(primary_key=True, serialize=False)),
                ('ee_estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estadoentrada',
                'ordering': ['ee_estado'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prov_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('prov_nombre', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('prov_estado', models.CharField(max_length=50, verbose_name='Estado del Proveedor (activo/inactivo)')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['prov_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('e_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('e_fecha', models.DateField(verbose_name='Fecha')),
                ('e_entrada', models.TimeField(verbose_name='Entrada')),
                ('e_salida', models.TimeField(verbose_name='Salida')),
                ('e_visita', models.CharField(blank=True, max_length=200, null=True, verbose_name='Visita')),
                ('e_comentario', models.CharField(blank=True, max_length=45, null=True, verbose_name='Comentario')),
                ('e_cob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='swap_porteria.cobrador', verbose_name='Cobrador')),
                ('e_fun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='swap_tthh.funcionarios', verbose_name='Funcionario')),
                ('e_ee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_porteria.estadoentrada', verbose_name='Estado')),
                ('e_prov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='swap_porteria.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'db_table': 'entrada',
                'ordering': ['e_fecha'],
            },
        ),
    ]
