# Generated by Django 5.2.1 on 2025-06-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swap_tthh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareadia',
            fields=[
                ('td_id', models.AutoField(primary_key=True, serialize=False)),
                ('td_dia', models.CharField(max_length=45, verbose_name='Dia')),
            ],
            options={
                'verbose_name': 'Dia de la Tarea',
                'verbose_name_plural': 'Dias de las Tareas',
                'db_table': 'tareadia',
            },
        ),
        migrations.CreateModel(
            name='Tareaestado',
            fields=[
                ('te_id', models.AutoField(primary_key=True, serialize=False)),
                ('te_estado', models.CharField(max_length=45, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado de Tarea',
                'verbose_name_plural': 'Estados de Tareas',
                'db_table': 'tareaestado',
                'ordering': ['te_estado'],
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('tarea_id', models.AutoField(primary_key=True, serialize=False)),
                ('tarea_titulo', models.CharField(max_length=50, verbose_name='Titulo de Tarea')),
                ('tarea_descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion de Tarea')),
                ('tarea_dpto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_tthh.departamentos', verbose_name='Departamento Pertinente')),
                ('tarea_td', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_home.tareadia', verbose_name='Dia de la Tarea')),
                ('tarea_te', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_home.tareaestado', verbose_name='Estado de la Tarea')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
                'ordering': ['tarea_titulo'],
            },
        ),
    ]
