# Generated by Django 5.2.1 on 2025-06-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('dpto_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('dpto_nombre', models.CharField(max_length=70, verbose_name='Nombre del Departamento')),
                ('dpto_estatus', models.CharField(max_length=45, verbose_name='Estatus del Departamento')),
                ('dpto_nombreorganizacion', models.CharField(max_length=70, verbose_name='Nombre de la Organizacion')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamentos',
                'ordering': ['dpto_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('fun_id', models.AutoField(primary_key=True, serialize=False)),
                ('fun_ci', models.PositiveBigIntegerField(verbose_name='Cedula de Identidad')),
                ('fun_nombres_apellidos', models.CharField(max_length=220, verbose_name='Nombres y Apellidos')),
                ('fun_correo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo Electronico')),
                ('fun_sueldo', models.BigIntegerField(verbose_name='Salario')),
                ('fun_cel', models.CharField(max_length=30, verbose_name='Numero de Celular')),
                ('fun_entrada', models.DateField(verbose_name='Fecha de Entrada a la Empresa')),
                ('fun_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida de la Empresa')),
                ('fun_estado', models.CharField(max_length=45, verbose_name='Estado(activo/inactivo)')),
                ('fun_dpto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_tthh.departamentos', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'funcionarios',
                'ordering': ['fun_nombres_apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Telefonosinternos',
            fields=[
                ('ti_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('ti_numero', models.PositiveSmallIntegerField(verbose_name='Numero de Telfefono Interno')),
                ('ti_fun', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_tthh.funcionarios', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Telefono Interno',
                'verbose_name_plural': 'Telefonos Internos',
                'db_table': 'telefonosinternos',
                'ordering': ['ti_numero'],
            },
        ),
    ]
