# Generated by Django 5.2.1 on 2025-06-24 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swap_porteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnicosmonto',
            fields=[
                ('tm_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('tm_monto', models.IntegerField(verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Monto',
                'verbose_name_plural': 'Montos',
                'db_table': 'tecnicosmonto',
                'ordering': ['tm_monto'],
            },
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('tec_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tec_fexacta', models.DateField(verbose_name='Fecha Exacta')),
                ('tec_hexacta', models.TimeField(verbose_name='Hora Exacta')),
                ('tec_sitios', models.CharField(blank=True, max_length=60, null=True, verbose_name='Sitio')),
                ('tec_cliente', models.CharField(max_length=60, verbose_name='Cliente')),
                ('tec_descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('tec_fecha', models.DateField(verbose_name='Fecha de Realizacion del Trabajo')),
                ('tec_hinicio', models.TimeField(verbose_name='Hora de inicio del Trabajo')),
                ('tec_hfinal', models.TimeField(verbose_name='Hora de Finalizacion del Trabajo')),
                ('tec_nombre', models.CharField(max_length=250, verbose_name='Nombre del Tecnico')),
                ('tec_ee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_porteria.estadoentrada', verbose_name='Estado')),
                ('tec_tm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='swap_serviciotecnico.tecnicosmonto', verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Tecnico',
                'verbose_name_plural': 'Tecnicos',
                'db_table': 'tecnicos',
                'ordering': ['tec_fecha'],
            },
        ),
    ]
